# flake8: noqa
try:
    from .version import *  # generated by scons
except ImportError:
    from ._version import *  # package is installed with setup.py for GHA

from .metadetect import (
    do_metadetect,
    Metadetect,
)
from . import metadetect
from . import fitting

from . import util
from . import defaults
from . import procflags
from . import shearpos
