name: tests

on:
  push:
    branches:
      - master
  pull_request: null

jobs:
  tests:
    name: tests
    strategy:
      matrix:
        pyver: [3.6, 3.7, 3.8]

    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.pyver }}
          channels: conda-forge,defaults
          channel-priority: strict
          show-channel-urls: true

      - name: configure conda and install code
        shell: bash -l {0}
        run: |
          conda config --set always_yes yes
          conda install --quiet --yes --file requirements.txt
          conda install --quiet --yes --file dev-requirements.txt
          pip install --progress-bar=off -r volatile-requirements.txt

          python -m pip install -e .

      - name: lint
        shell: bash -l {0}
        run: |
          flake8 metadetect

      - name: test
        shell: bash -l {0}
        run: |
          pytest -vvs metadetect
