name: tests

on:
  push:
    branches:
      - master
  pull_request: null

jobs:
  tests:
    name: tests
    strategy:
      matrix:
        pyver: ["3.9", "3.10", "3.11", "3.12"]

    runs-on: "ubuntu-latest"

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.pyver }}
          channels: conda-forge,defaults
          channel-priority: strict
          show-channel-urls: true
          miniforge-version: latest

      - name: configure conda and install code
        shell: bash -l {0}
        run: |
          conda config --set always_yes yes
          conda install --quiet --yes --file requirements.txt
          conda install --quiet --yes --file dev-requirements.txt

          python -m pip install -e .

      - name: lint
        shell: bash -l {0}
        run: |
          flake8 metadetect

      - name: test
        shell: bash -l {0}
        run: |
          # don't run metadetect/lsst/tests
          pytest -v -n 4 --cov=metadetect --cov-report term-missing metadetect/tests
          pytest -vvs shear_meas_test/test_shear_meas.py -k test_shear_meas_timing --log-cli-level=info
          pytest -vvs shear_meas_test/test_shear_meas.py -k test_shear_meas_simple[wmom-1000000.0-7-64]
          pytest -vvs shear_meas_test/test_shear_meas.py -k test_shear_meas_simple[ksigma-1000000.0-7-64]
          pytest -vvs shear_meas_test/test_shear_meas.py -k test_shear_meas_simple[pgauss-1000000.0-7-64]
          pytest -vvs shear_meas_test/test_shear_meas.py -k test_shear_meas_simple[am-1000000.0-7-64]
          pytest -vvs shear_meas_test/test_shear_meas.py -k test_shear_meas_simple[gauss-1000000.0-7-64]
          pytest -vvs shear_meas_test/test_shear_meas.py -k test_shear_meas_color[wmom-1000000.0-7-64]
          pytest -vvs shear_meas_test/test_shear_meas.py -k test_shear_meas_color[pgauss-1000000.0-7-64]
